apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: nodejs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: 80963/minikube:frontend
        imagePullPolicy: IfNotPresent
        name: frontend
