apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: python-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: 80963/minikube:backend
        imagePullPolicy: IfNotPresent
        name: backend
